[package]
name = "betterbase-accounts-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
hex.workspace = true
base64.workspace = true
bs58.workspace = true
chrono.workspace = true
hmac.workspace = true
jsonwebtoken.workspace = true
betterbase-accounts-core = { path = "../core" }
betterbase-accounts-storage = { path = "../storage" }
opaque-ke.workspace = true
p256.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
uuid.workspace = true
