[package]
name = "less-accounts-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
hex.workspace = true
less-accounts-api = { path = "../api" }
less-accounts-auth = { path = "../auth" }
less-accounts-cap = { path = "../cap" }
less-accounts-core = { path = "../core" }
less-accounts-email = { path = "../email" }
less-accounts-storage = { path = "../storage" }
rand.workspace = true
tokio.workspace = true
tracing.workspace = true
