[package]
name = "less-accounts-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
hex.workspace = true
http.workspace = true
less-accounts-auth = { path = "../auth" }
less-accounts-cap = { path = "../cap" }
less-accounts-core = { path = "../core" }
less-accounts-email = { path = "../email" }
less-accounts-storage = { path = "../storage" }
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tower.workspace = true
