[package]
name = "less-accounts-oauth-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
less-accounts-storage = { path = "../../crates/storage" }
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true
