[package]
name = "betterbase-accounts-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "betterbase-accounts server binary"

[dependencies]
anyhow.workspace = true
betterbase-accounts-app = { path = "../../crates/app" }
tokio.workspace = true
tracing-subscriber.workspace = true
